# @package _global_

defaults:
  - /dataset: imagenet
  - /callbacks/ema_callback
  - _self_

system:
  _target_: system.system_timm_base.LightningSystem
  _recursive_: false

model_name: "tmp_rsb"
batch_size: 128
num_workers: 4

# --------------------------------- backbone --------------------------------- #
model:
  _target_: timm.models.create_model
  model_name: resnet50
  pretrained: false
  num_classes: 1000
  drop_path_rate: 0 # for a1 and a2: 0.05

# ------------------------------ transformation ------------------------------ #
image_size: 224
label_smoothing: 0
train_transform:
  _target_: timm.data.create_transform
  input_size: 160
  is_training: true
  color_jitter: null
  auto_augment: rand-m6-mstd0.5-inc1
  interpolation: bicubic

val_transform:
  _target_: timm.data.create_transform
  input_size: ${image_size}
  is_training: False
  interpolation: bicubic
  crop_pct: 0.95

mixup_fn:
  _target_: timm.data.Mixup
  mixup_alpha: 0.1
  cutmix_alpha: 1.0
  label_smoothing: ${label_smoothing}
  num_classes: 1000

# --------------------------------- optimizer -------------------------------- #
optimizer:
  _target_: timm.optim.create_optimizer_v2
  opt: lamb
  lr: 8e-3
  weight_decay: 0.02

# --------------------------------- scheduler -------------------------------- #
lr_schedule:
  _target_: utils.utils.cosine_scheduler
  base_value: null
  final_value: 1e-6
  epochs: ${trainer.max_epochs}
  niter_per_ep: null
  warmup_epochs: 5
  start_warmup_value: 0

wd_schedule: null

# ------------------------------ training params ----------------------------- #
criterion:
  _target_: timm.loss.BinaryCrossEntropy

base_lr: 8e-3
base_batch_size: 2048

trainer:
  max_epochs: 100
  precision: 16
