# @package _global_

dataset:
  name: cifar10
  instance:
    _target_: datamodules.cifar10.CIFAR10DataModule
    data_dir: data/cifar10
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: true
    pin_memory: true
    drop_last: true
