# @package _global_

callbacks:
  model_checkpoint:
    _target_: callbacks.custom_callbacks.CheckpointCallback
    monitor: "val/loss" # name of the logged metric which determines when model is improving
    save_top_k: 1 # save k best models (determined by above metric)
    save_last: True # additionaly always save model from last epoch
    mode: "min" # can be "max" or "min"
    filename: "{epoch:03d}"
    dirpath: ${trainer.weights_save_path}
    verbose: true
    save_on_train_epoch_end: false
    every_n_epochs: 1
